### ISSUE TITLE
Play-scala-mongodb throws exception and quits when accessing /db

### ISSUE THREAD

**Issue by aschneider-techempower** [TechEmpower/FrameworkBenchmarks#1218]
```
[WARN] [11/10/2014 16:45:12.256] [New I/O worker #1] [EventStream(akka://play)] [akka.event-handlers] config is deprecated, use [akka.loggers]
[ERROR] [11/10/2014 16:45:12.285] [reactivemongo-akka.actor.default-dispatcher-2] [ActorSystem(reactivemongo)] Uncaught error from thread [reactivemongo-akka.actor.default-dispatcher-2] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.NoSuchMethodError: akka.actor.ActorSystem.dispatcher()Lakka/dispatch/MessageDispatcher;
	at reactivemongo.core.actors.MongoDBSystem.<init>(actors.scala:121)
	at reactivemongo.api.MongoDriver$$anonfun$3.apply(api.scala:238)
	at reactivemongo.api.MongoDriver$$anonfun$3.apply(api.scala:238)
	at akka.actor.CreatorFunctionConsumer.produce(Props.scala:369)
	at akka.actor.Props.newActor(Props.scala:323)
	at akka.actor.ActorCell.newActor(ActorCell.scala:534)
	at akka.actor.ActorCell.create(ActorCell.scala:560)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:425)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:447)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:262)
	at akka.dispatch.Mailbox.run(Mailbox.scala:218)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[ERROR] [11/10/2014 16:45:12.291] [reactivemongo-akka.actor.default-dispatcher-4] [akka://reactivemongo/user/$a] head of empty list
java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:337)
	at scala.collection.immutable.Nil$.head(List.scala:334)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
	at akka.actor.ActorCell.invoke(ActorCell.scala:456)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[ERROR] [11/10/2014 16:45:12.293] [reactivemongo-akka.actor.default-dispatcher-5] [akka://reactivemongo/user/$a] changing Recreate into Create after java.util.NoSuchElementException: head of empty list
[info] application - ReactiveMongoPlugin stops, closing connections...
```

Exception's not really very helpful. I've found a couple of [links](https://groups.google.com/forum/#!msg/reactivemongo/pYfI8a2eDxw/E9p7tQwLga8J) that hint towards the problem relating to the mongodb driver, but I've been unable to debug this. 

Perhaps someone who knows more Scala can help.

**Comment by LadyMozzarella** [comment]
I have play-scala-mongodb as passing on master. Good to close?
![play-scala-mongodb](https://cloud.githubusercontent.com/assets/4926965/6471936/d3431b96-c1a3-11e4-9bc7-52d4b409fcc6.png)
