### ISSUE TITLE
Perl Errors in Travis CI

### ISSUE THREAD

**Issue by LadyMozzarella** [TechEmpower/FrameworkBenchmarks#1366]
I can't tell if these are temporary bugs in Travis or not. I don't think it's me because I'm testing two different branches and getting the same errors. First, all of my Perl tests from both [LadyMozzarella:i1291-update-nginx-to-stable](https://travis-ci.org/LadyMozzarella/FrameworkBenchmarks/builds/53125217) and [LadyMozzarella:i1095-add-json-extension-to-benchmark_config](https://travis-ci.org/LadyMozzarella/FrameworkBenchmarks/builds/53125739) were erroring. Some of them are rarely passing now, but I've been rerunning them to see what happens. Most of the time i've been getting this error:

```bash
Fetching http://www.cpan.org/authors/id/R/RE/REHSACK/File-ShareDir-1.102.tar.gz ... 

No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

The build has been terminated
```

I got errors in both runs on mojolicious (but works fine locally).

[mojolicious errors](https://travis-ci.org/LadyMozzarella/FrameworkBenchmarks/jobs/53125289):
```bash
Accessing URL http://127.0.0.1:8080/db
  Response (trimmed to 40 bytes): "{"randomNumber":null,"id":2721}"
WARNING:root:Verifying test db for mojolicious caused an exception: float() argument must be a string or a number
   FAIL for http://127.0.0.1:8080
     Caused Exception in TFB
               This almost certainly means your return value is incorrect, 
               but also that you have found a bug. Please submit an issue
               including this message: float() argument must be a string or a number
     Traceback (most recent call last):
       File "/home/travis/build/LadyMozzarella/FrameworkBenchmarks/toolset/benchmark/framework_test.py", line 279, in verify_type
         results = test.verify(base_url)
       File "/home/travis/build/LadyMozzarella/FrameworkBenchmarks/toolset/benchmark/test_types/db_type.py", line 49, in verify
         problems += self._verifyObject(response, url)
       File "/home/travis/build/LadyMozzarella/FrameworkBenchmarks/toolset/benchmark/test_types/db_type.py", line 88, in _verifyObject
         float(db_object["randomnumber"])
     TypeError: float() argument must be a string or a number
.
.
.
Accessing URL http://127.0.0.1:8080/queries?queries=2
  Response (trimmed to 40 bytes): "[{"randomNumber":null,"id":3369},{"id":2"
WARNING:root:Verifying test query for mojolicious caused an exception: float() argument must be a string or a number
   FAIL for http://127.0.0.1:8080
     Caused Exception in TFB
               This almost certainly means your return value is incorrect, 
               but also that you have found a bug. Please submit an issue
               including this message: float() argument must be a string or a number
     Traceback (most recent call last):
       File "/home/travis/build/LadyMozzarella/FrameworkBenchmarks/toolset/benchmark/framework_test.py", line 279, in verify_type
         results = test.verify(base_url)
       File "/home/travis/build/LadyMozzarella/FrameworkBenchmarks/toolset/benchmark/test_types/query_type.py", line 28, in verify
         problems += self._verifyQueryList(2, body, url + '2')
       File "/home/travis/build/LadyMozzarella/FrameworkBenchmarks/toolset/benchmark/test_types/query_type.py", line 93, in _verifyQueryList
         obj_ok = self._verifyObject(item, url, max_infraction)
       File "/home/travis/build/LadyMozzarella/FrameworkBenchmarks/toolset/benchmark/test_types/db_type.py", line 88, in _verifyObject
         float(db_object["randomnumber"])
     TypeError: float() argument must be a string or a number
```

**Comment by hamiltont** [comment]
FYI, in addition to whatever is causing mojo to return null, that error message is still correct - that's a bug in TFB (I love this error message, it's ended up helping us find like 5-10 errors now!). `db_type.py` should check if `db_object["randomnumber"]` is null before trying to get a float out of it, and print a nice error message to the user saying something like "X returned null instead of a numeric value". The other `*_type.py` files may have similar errors

@jberger can you think of any reason mojo would *not* work for URL `http://127.0.0.1:8080/queries?queries=2` and `http://127.0.0.1:8080/db`, but would work correctly for URL `http://127.0.0.1:8080/updates?queries=2` - are there substantial differences in how those URLs are handled internally? The most relevant logs start [here](https://travis-ci.org/LadyMozzarella/FrameworkBenchmarks/jobs/53125811#L2733)

Currently my only thought is that perhaps mongodb is not turning on. I've read the entire log as carefully as possible, and disregarding some errors from postgres that are unrelated (this uses mongo), there are no errors listed above the point where the verification fails. So basically I have no solid idea what's going wrong here...

**Comment by hamiltont** [comment]
@LadyMozzarella perhaps rebasing onto master would also give some valuable info - I just merged #1357

**Comment by LadyMozzarella** [comment]
The perl test errors appear to have stopped (yay), but I'm noticing the same TFB style of errors on kelp and mojolicious. I'm assuming kelp is another separate bug?

The [errors in Travis](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/builds/53725686) on [commit #2114738](https://github.com/TechEmpower/FrameworkBenchmarks/commit/211473859f9a143b5ae6bcf35a04db3e4b5becb7), which was merged after #1357:

* Test ['kelp'](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/53725757#L3157)

  ```bash
Accessing URL http://127.0.0.1:8080/db
  Response (trimmed to 40 bytes): "[]"
WARNING:root:Verifying test db for kelp caused an exception: list index out of range
   FAIL for http://127.0.0.1:8080
     Caused Exception in TFB
               This almost certainly means your return value is incorrect, 
               but also that you have found a bug. Please submit an issue
               including this message: list index out of range
     Traceback (most recent call last):
       File "/home/travis/build/TechEmpower/FrameworkBenchmarks/toolset/benchmark/framework_test.py", line 279, in verify_type
         results = test.verify(base_url)
       File "/home/travis/build/TechEmpower/FrameworkBenchmarks/toolset/benchmark/test_types/db_type.py", line 41, in verify
         response = response[0]
     IndexError: list index out of range
```

* Test ['kelp-mongodb'](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/53725757#L3242)

  ```bash
Accessing URL http://127.0.0.1:8080/db
  Response (trimmed to 40 bytes): "[]"
WARNING:root:Verifying test db for kelp-mongodb caused an exception: list index out of range
   FAIL for http://127.0.0.1:8080
     Caused Exception in TFB
               This almost certainly means your return value is incorrect, 
               but also that you have found a bug. Please submit an issue
               including this message: list index out of range
     Traceback (most recent call last):
       File "/home/travis/build/TechEmpower/FrameworkBenchmarks/toolset/benchmark/framework_test.py", line 279, in verify_type
         results = test.verify(base_url)
       File "/home/travis/build/TechEmpower/FrameworkBenchmarks/toolset/benchmark/test_types/db_type.py", line 41, in verify
         response = response[0]
```

* Test ['mojolicious'](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/53725758#L2762)

  ```bash
Accessing URL http://127.0.0.1:8080/queries?queries=2
  Response (trimmed to 40 bytes): "[{"randomNumber":null,"id":3919},{"id":7"
WARNING:root:Verifying test query for mojolicious caused an exception: float() argument must be a string or a number
   FAIL for http://127.0.0.1:8080
     Caused Exception in TFB
               This almost certainly means your return value is incorrect, 
               but also that you have found a bug. Please submit an issue
               including this message: float() argument must be a string or a number
     Traceback (most recent call last):
       File "/home/travis/build/TechEmpower/FrameworkBenchmarks/toolset/benchmark/framework_test.py", line 279, in verify_type
         results = test.verify(base_url)
       File "/home/travis/build/TechEmpower/FrameworkBenchmarks/toolset/benchmark/test_types/query_type.py", line 28, in verify
         problems += self._verifyQueryList(2, body, url + '2')
       File "/home/travis/build/TechEmpower/FrameworkBenchmarks/toolset/benchmark/test_types/query_type.py", line 93, in _verifyQueryList
         obj_ok = self._verifyObject(item, url, max_infraction)
       File "/home/travis/build/TechEmpower/FrameworkBenchmarks/toolset/benchmark/test_types/db_type.py", line 88, in _verifyObject
         float(db_object["randomnumber"])
     TypeError: float() argument must be a string or a number
```

**Comment by jberger** [comment]
My best answer, at least for Mojolicious is presented in #1411 . MongoDB is hosed, port to Postgres.

**Comment by LadyMozzarella** [comment]
Closing. No longer seeing perl errors on Travis. :)
