### ISSUE TITLE
NPE in Grizzly when no parameters

### ISSUE THREAD

**Issue by denkab** [TechEmpower/FrameworkBenchmarks#1663]
Round 11 preview 1:

Server grizzly-jersey: java.lang.NumberFormatException: null
Server grizzly-jersey: 	at java.lang.Integer.parseInt(Integer.java:454)
Server grizzly-jersey: 	at java.lang.Integer.parseInt(Integer.java:527)
Server grizzly-jersey: 	at hello.DbResource.getQueries(DbResource.java:70)

**Comment by denkab** [comment]
I broke it, so I'll be fixing it.
