### ISSUE TITLE
sinatra-postgres-passenger-mri failing validation in a Vagrant environment

### ISSUE THREAD

**Issue by zloster** [TechEmpower/FrameworkBenchmarks#2809]
I've attempted a run in a Vagrant environment using the following command:

> ~~vagrant@tfb-all:~/FrameworkBenchmarks$tfb -m benchmark --test servant,sinatra-postgres-passenger-mri~~ Updated:

> vagrant@tfb-all:~/FrameworkBenchmarks$tfb -m benchmark --test servant sinatra-postgres-passenger-mri

`servant` tests passed and gave results but `sinatra-postgres-passenger-mri` gave errors like this:

```
 Caused Exception in TFB
                 This almost certainly means your return value is incorrect,
                 but also that you have found a bug. Please submit an issue
                 including this message: HTTPConnectionPool(host='TFB-server', port=8080): Read timed out. (read timeout=15)
     Traceback (most recent call last):
       File "/home/vagrant/FrameworkBenchmarks/toolset/benchmark/framework_test.py", line 387, in verify_type
         results = test.verify(base_url)
       File "/home/vagrant/FrameworkBenchmarks/toolset/benchmark/test_types/plaintext_type.py", line 18, in verify
         headers, body = self.request_headers_and_body(url)
       File "/home/vagrant/FrameworkBenchmarks/toolset/benchmark/test_types/framework_test_type.py", line 85, in request_headers_and_body
         r = requests.get(url, timeout=15, headers=headers)
       File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
         return request('get', url, **kwargs)
       File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
         return session.request(method=method, url=url, **kwargs)
       File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
         resp = self.send(prep, **send_kwargs)
       File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
         r = adapter.send(request, **kwargs)
       File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 387, in send
         raise Timeout(e)
     Timeout: HTTPConnectionPool(host='TFB-server', port=8080): Read timed out. (read timeout=15)
     See http://frameworkbenchmarks.readthedocs.org/en/latest/Project-Information/Framework-Tests/#specific-test-requirements

 Caused Exception in TFB
                 This almost certainly means your return value is incorrect,
                 but also that you have found a bug. Please submit an issue
                 including this message: HTTPConnectionPool(host='TFB-server', port=8080): Read timed out. (read timeout=15)
     Traceback (most recent call last):
       File "/home/vagrant/FrameworkBenchmarks/toolset/benchmark/framework_test.py", line 387, in verify_type
         results = test.verify(base_url)
       File "/home/vagrant/FrameworkBenchmarks/toolset/benchmark/test_types/plaintext_type.py", line 18, in verify
         headers, body = self.request_headers_and_body(url)
       File "/home/vagrant/FrameworkBenchmarks/toolset/benchmark/test_types/framework_test_type.py", line 85, in request_headers_and_body
         r = requests.get(url, timeout=15, headers=headers)
       File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
         return request('get', url, **kwargs)
       File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
         return session.request(method=method, url=url, **kwargs)
       File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
         resp = self.send(prep, **send_kwargs)
       File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
         r = adapter.send(request, **kwargs)
       File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 387, in send
         raise Timeout(e)
     Timeout: HTTPConnectionPool(host='TFB-server', port=8080): Read timed out. (read timeout=15)
     See http://frameworkbenchmarks.readthedocs.org/en/latest/Project-Information/Framework-Tests/#specific-test-requirements
```

The source code was updated today but the Vagrant VM is 2 or 3 months old. The ping to `TFB-server` is working:

> Results are saved in /home/vagrant/FrameworkBenchmarks/results/20170522094318
> vagrant@tfb-all:~/FrameworkBenchmarks$ ping TFB-server
> PING TFB-server (127.0.0.1) 56(84) bytes of data.
> 64 bytes from TFB-all (127.0.0.1): icmp_seq=1 ttl=64 time=0.137 ms
> 64 bytes from TFB-all (127.0.0.1): icmp_seq=2 ttl=64 time=0.192 ms
> 64 bytes from TFB-all (127.0.0.1): icmp_seq=3 ttl=64 time=0.256 ms
> 64 bytes from TFB-all (127.0.0.1): icmp_seq=4 ttl=64 time=0.259 ms
> 64 bytes from TFB-all (127.0.0.1): icmp_seq=5 ttl=64 time=0.264 ms
>

**Comment by nbrady-techempower** [comment]
`servant,sinatra-postgres-passenger-mri`

Did you try running `sinatra-postgres-passenger-mri` by iteself? The tests are not comma separated.

**Comment by zloster** [comment]
Sorry, copy-pasted the wrong command.
Yes, I've run it by itself and the problem is the same. Here are the logs from the run: http://sprunge.us/NTfE

**Comment by nbrady-techempower** [comment]
Thanks, spinning up a new vm and checking it out now

**Comment by nbrady-techempower** [comment]
@zloster Ok, I was able to get this to pass: http://sprunge.us/DDhC

The problem for me stemmed from: http://joequery.me/guides/bundle-install-text-file-busy/

I changed the path in `Ruby/sinatra/config/bundle_install.sh` to:

`bundle install --jobs=4 --gemfile=$TROOT/Gemfile --path=$IROOT/sinatra/bundle`

Ideally, all frameworks that install anything should be installing them to the IROOT folder but particularly, bundle runs in to a problem sometimes when the folder is shared.

Submitting a fix shortly.
