### ISSUE TITLE
[h2o.cr] How the figure out cannot start error?

### ISSUE THREAD

**Issue by S-YOU** [TechEmpower/FrameworkBenchmarks#4156]
It seems like library I've submitted has errors on recent runs

https://tfb-status.techempower.com/results/856ec8af-7881-4e36-a794-9b7d4caabcc0
https://tfb-status.techempower.com/raw/results.2018-10-23-20-51-40-262.json

```
[h2o.cr] had problems starting or stopping

"h2o.cr": "ERROR: Problem starting h2o.cr", 
```

I am wondering how to troubleshoot this issue. Any more information would be great.

**Comment by nbrady-techempower** [comment]
If you click on browse near the results.zip in the first link you provided, you can get to the logs.

https://tfb-status.techempower.com/unzip/results.2018-10-23-20-47-00-067.zip/results/20181021173347/h2o.cr/build/h2o.cr.log

**Comment by nbrady-techempower** [comment]
This test is also failing on travis and for me locally now with a missing package:

```
--------------------------------------------------------------------------------
Running Test: h2o.cr
--------------------------------------------------------------------------------
h2o.cr: Step 1/11 : FROM debian:testing
h2o.cr:  ---> eadfca9546a1
h2o.cr: Step 2/11 : RUN apt update   && apt install -yqq libh2o-evloop-dev libwslay-dev libyaml-0-2 libevent-dev libpcre3-dev     gcc wget git libssl-dev libuv1-dev ca-c
ertificates --no-install-recommends
h2o.cr:  ---> Running in ec90f14c5111
h2o.cr:
h2o.cr: WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
h2o.cr: Get:1 http://cdn-fastly.deb.debian.org/debian testing InRelease [150 kB]
h2o.cr: Get:2 http://cdn-fastly.deb.debian.org/debian testing/main amd64 Packages [7696 kB]
h2o.cr: Fetched 7845 kB in 4s (2062 kB/s)
h2o.cr: Reading package lists...
h2o.cr: Building dependency tree...
h2o.cr: Reading state information...
h2o.cr: 14 packages can be upgraded. Run 'apt list --upgradable' to see them.
h2o.cr:
h2o.cr: WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
h2o.cr:
h2o.cr: E: Unable to locate package libh2o-evloop-dev
h2o.cr: Removing intermediate container ec90f14c5111
h2o.cr: Docker build failed; terminating
h2o.cr: Traceback (most recent call last):
h2o.cr:   File "/FrameworkBenchmarks/toolset/utils/docker_helper.py", line 51, in __build
h2o.cr:     raise Exception(token['errorDetail']['message'])
h2o.cr: Exception: The command '/bin/sh -c apt update   && apt install -yqq libh2o-evloop-dev libwslay-dev libyaml-0-2 libevent-dev libpcre3-dev     gcc wget git libssl-
dev libuv1-dev ca-certificates --no-install-recommends' returned a non-zero code: 100
```

**Comment by S-YOU** [comment]
Ah, because of I am using debian:testing, I will fix. Thanks.

**Comment by nbrady-techempower** [comment]
Yeah I didn't see the `debian:testing` thing until after. Will make sense to change it to something more stable. I'll close this issue, thanks!

**Comment by faustinoaq** [comment]
Hi @S-YOU looks like h2o.cr is failing again :sweat_smile: 

https://tfb-status.techempower.com/unzip/results.2019-01-25-04-03-03-475.zip/results/20190122031823/h2o.cr/build/h2o.cr.log

```
h2o.cr: Step 1/10 : FROM alpine:edge
h2o.cr:  ---> dacde26455ab
h2o.cr: Step 2/10 : RUN apk --update --no-cache add gcc git ca-certificates libc-dev openssl1.0-dev h2o-dev wslay-dev crystal shards
h2o.cr:  ---> Running in 719d33733ad0
h2o.cr: fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
h2o.cr: fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
h2o.cr: ERROR: unsatisfiable constraints:
h2o.cr:   openssl1.0-dev (missing):
h2o.cr:     required by: world[openssl1.0-dev]
h2o.cr: Removing intermediate container 719d33733ad0
h2o.cr: Docker build failed; terminating
h2o.cr: Traceback (most recent call last):
h2o.cr:   File "/FrameworkBenchmarks/toolset/utils/docker_helper.py", line 55, in __build
h2o.cr:     raise Exception(token['errorDetail']['message'])
h2o.cr: Exception: The command '/bin/sh -c apk --update --no-cache add gcc git ca-certificates libc-dev openssl1.0-dev h2o-dev wslay-dev crystal shards' returned a non-zero code: 1
h2o.cr: Build time: 1s
```

Seems an Alpine issue, WDYT?

**Comment by S-YOU** [comment]
yeah, alpine:edge was too fragile I guess. I was hesitant to compile h2o myself. I will find my time to build again. thanks for letting me know.
