### ISSUE TITLE
is something wrong with the test server ？

### ISSUE THREAD

**Issue by kyle2008** [TechEmpower/FrameworkBenchmarks#4243]
see the leasted test 
https://tfb-status.techempower.com

**Comment by msmith-techempower** [comment]
Yes, that run stalled.

Essentially, continuous runs build up junk on the disk and we eventually run out of disk space:

```
	--------------------------------------------------------------------------------
	Benchmarking cppcms-postgres
	--------------------------------------------------------------------------------
	BENCHMARKING DB ...
	Benchmark results:
	Complete
	BENCHMARKING JSON ...
	Benchmark results:
	Complete
	BENCHMARKING QUERY ...
	Benchmark results:
	Complete
	BENCHMARKING UPDATE ...
	Benchmark results:
	Complete
	BENCHMARKING FORTUNE ...
	Benchmark results:
	Complete
	BENCHMARKING PLAINTEXT ...
	Benchmark results:
	Complete
	BENCHMARKING CACHED_QUERY ...
	cppcms-postgres: Traceback (most recent call last):
	cppcms-postgres:   File "/FrameworkBenchmarks/toolset/benchmark/benchmarker.py", line 190, in __run_test
	cppcms-postgres:     self.__benchmark(test, benchmark_log)
	cppcms-postgres:   File "/FrameworkBenchmarks/toolset/benchmark/benchmarker.py", line 276, in __benchmark
	cppcms-postgres:     benchmark_type(test_type)
	cppcms-postgres:   File "/FrameworkBenchmarks/toolset/benchmark/benchmarker.py", line 266, in benchmark_type
	cppcms-postgres:     results = self.results.parse_test(framework_test, test_type)
	cppcms-postgres:   File "/FrameworkBenchmarks/toolset/utils/results.py", line 169, in parse_test
	cppcms-postgres:     "w") as stats_file:
	cppcms-postgres: IOError: [Errno 28] No space left on device: u'/FrameworkBenchmarks/results/20181204011908/cppcms-postgres/cached_query/stats.txt.json'
	cppcms-postgres: Error during test: cppcms-postgres
	cppcms-postgres: Total test time: 15m 13s
```

I've kicked off another run (there should be enough space now), and we have a mechanism in place to check if we have 30GB of disk space available at the end of a run and clean out all the docker cruft if not; however, it is looking more and more likely that 30GB is not enough space. May have to kick that up to 50GB.

Thanks for reporting! We will get the stalled run cleared off of https://tfb-status.techempower.com soon.
