### ISSUE TITLE
Empty results in last test run

### ISSUE THREAD

**Issue by fafhrd91** [TechEmpower/FrameworkBenchmarks#4687]
I see some empty result for current [run of continuous benchmarck](https://tfb-status.techempower.com/results/76a34044-54d6-4349-adfe-863c2d5ae756)
specifically for actix-core, actix-pg, actix-dieses. but those are in "succeeded" list.
is this something wrong with framework code?

**Comment by nbrady-techempower** [comment]
The start time - end time makes it seem like something went wrong during the testing process.. Will take a look at the logs shortly. A little backed up atm.

**Comment by michaelhixson** [comment]
There is a bunch of this in actix-core's run log:

```
[techempower@tfb ~]$ less FrameworkBenchmarks/results/20190422154321/actix-core/run/actix-core.log
actix-core: Started http server: 127.0.0.1:8080
actix-core: thread 'actix-rt:worker:13' panicked at 'assertion failed: self.remaining_mut() >= src.len()', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/bytes-0.4.12/src/bytes.rs:1542:9
actix-core: note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
actix-core: Panic in Arbiter thread, shutting down system.
actix-core: thread 'actix-rt:worker:8' panicked at 'assertion failed: self.remaining_mut() >= src.len()', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/bytes-0.4.12/src/bytes.rs:1542:9
actix-core: Panic in Arbiter thread, shutting down system.
actix-core: thread 'actix-rt:worker:12' panicked at 'assertion failed: self.remaining_mut() >= src.len()', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/bytes-0.4.12/src/bytes.rs:1542:9
actix-core: Panic in Arbiter thread, shutting down system.
actix-core: thread 'actix-rt:worker:14' panicked at 'assertion failed: self.remaining_mut() >= src.len()', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/bytes-0.4.12/src/bytes.rs:1542:9
```

**Comment by fafhrd91** [comment]
thanks!
