### ISSUE TITLE
Getting error on manual setup.

### ISSUE THREAD

**Issue by richardcatlin** [TechEmpower/FrameworkBenchmarks#496]
When I run this command, the install.log shows this error.  I am running on EC2 with m1.large Ubuntu instances.
toolset/run-tests.py -s 10.118.245.177 -c 10.38.14.191 -i ~/.ssh/blockhead.pem --install-software --list-tests &> install.log

Traceback (most recent call last):
  File "toolset/run-tests.py", line 54, in <module>
    benchmarker = Benchmarker(vars(args))
  File "/home/ubuntu/FrameworkBenchmarks/toolset/benchmark/benchmarker.py", line 589, in __init__
    self.database_ssh_string = "ssh -T -o StrictHostKeyChecking=no " + self.database_user + "@" + self.database_host
TypeError: cannot concatenate 'str' and 'NoneType' objects

Thanks,
Richard Catlin

**Comment by LadyMozzarella** [comment]
Closing this issue due to inactivity.
