### ISSUE TITLE
Failure during verification

### ISSUE THREAD

**Issue by tomas-langer** [TechEmpower/FrameworkBenchmarks#6080]
### OS (Please include kernel version)
MacOS X - Mojave

### Actual Behavior
The following message was printed:
```
Verifying test update for helidon-mp caused an exception: int() argument must be a string or a number, not 'NoneType'
   FAIL for http://tfb-server:8080
     Caused Exception in TFB
                 This almost certainly means your return value is incorrect,
                 but also that you have found a bug. Please submit an issue
                 including this message: int() argument must be a string or a number, not 'NoneType'
     Traceback (most recent call last):
       File "/FrameworkBenchmarks/toolset/benchmark/framework_test.py", line 113, in verify_type
         results = test.verify(base_url)
       File "/FrameworkBenchmarks/toolset/test_types/update/update.py", line 31, in verify
         problems = verify_query_cases(self, cases, url, True)
       File "/FrameworkBenchmarks/toolset/test_types/verifications.py", line 401, in verify_query_cases
         expected_rows, check_updates)
       File "/FrameworkBenchmarks/toolset/test_types/verifications.py", line 423, in verify_queries_count
         check_updates)
       File "/FrameworkBenchmarks/toolset/databases/abstract_database.py", line 88, in verify_queries
         rows_updated = int(cls.get_rows_updated(config))
     TypeError: int() argument must be a string or a number, not 'NoneType'
     See https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Framework-Tests-Overview#specific-test-requirements
{'Date': 'Tue, 13 Oct 2020 14:32:16 GMT', 'connection': 'keep-alive', 'Content-Type': 'application/json', 'content-length': '33', 'Server': 'helidon'}
[{"id":5281,"randomNumber":4056}]
```

**Comment by tomas-langer** [comment]
Postgres
I think there was a problem that no actual query/update was executed against the database due to aggressive caching of JPA.
I had to disable this test (problem on framework side with disabling caching of JPA, not on your side).

**Comment by itsumura-h** [comment]
I got the same error. It happens only `update` test.
It run on `Ubuntu 18.04.5 LTS`

**Comment by NateBrady23** [comment]
Closing as part of bulk cleanup.
