### ISSUE TITLE
Citrine problem with ubuntu 21.04 docker image

### ISSUE THREAD

**Issue by joanhey** [TechEmpower/FrameworkBenchmarks#6591]
In local and github actions build without problems.

But in Citrine:
```
nginx: Step 1/7 : FROM ubuntu:21.04
nginx:  ---> 01244e8938d1
nginx: Step 2/7 : ARG DEBIAN_FRONTEND=noninteractive
nginx:  ---> Running in cd4a5bc23243
nginx: Removing intermediate container cd4a5bc23243
nginx:  ---> 62b4a4a7ea86
nginx: Step 3/7 : RUN apt-get update -yqq
nginx:  ---> Running in ebd3e811f3fa
nginx: W: GPG error: http://security.ubuntu.com/ubuntu hirsute-security InRelease: gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed
nginx: E: The repository 'http://security.ubuntu.com/ubuntu hirsute-security InRelease' is not signed.
nginx: W: GPG error: http://archive.ubuntu.com/ubuntu hirsute InRelease: gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed
nginx: E: The repository 'http://archive.ubuntu.com/ubuntu hirsute InRelease' is not signed.
nginx: W: GPG error: http://archive.ubuntu.com/ubuntu hirsute-updates InRelease: gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed
nginx: E: The repository 'http://archive.ubuntu.com/ubuntu hirsute-updates InRelease' is not signed.
nginx: W: GPG error: http://archive.ubuntu.com/ubuntu hirsute-backports InRelease: gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed
nginx: E: The repository 'http://archive.ubuntu.com/ubuntu hirsute-backports InRelease' is not signed.
nginx: Removing intermediate container ebd3e811f3fa
nginx: Docker build failed; terminating
nginx: Traceback (most recent call last):
nginx:   File "/FrameworkBenchmarks/toolset/utils/docker_helper.py", line 55, in __build
nginx:     raise Exception(token['errorDetail']['message'])
nginx: Exception: The command '/bin/sh -c apt-get update -yqq' returned a non-zero code: 100
nginx: Build time: 5s

```

In the actual run will fail all the docker builts using ubuntu 21.04.

Posible solutions:

Update image and docker version: 
https://stackoverflow.com/questions/66319610/gpg-error-in-ubuntu-21-04-after-second-apt-get-update-during-docker-build

Free hardisk space:
https://stackoverflow.com/questions/59139453/repository-is-not-signed-in-docker-build
This one posible affect  #6582

**Comment by nbrady-techempower** [comment]
Thanks @joanhey! Pinging the team to see if anyone has time to address this today.

**Comment by nbrady-techempower** [comment]
@joanhey Looks like we're going to want to update docker on all the machines, but we're probably not going to get to that this week. We're at like 120% capacity on client work and on the off chance something breaks because of the update, we won't have time to fix it. It looks like only 2 tests are failing because of this specific issue (that I can tell for now), so the best bet might be to change the base image.

I'll leave this open so we can get to it as soon as we have time.

**Comment by fafhrd91** [comment]
Hey @nbrady-techempower, do you have any eta for this task? would be great to be able to bench uring

**Comment by nbrady-techempower** [comment]
@joanhey @fafhrd91 

Docker and Ubuntu have been updated on all machines. Tests are up and running again. If you guys see anything suspicious with test results, please let me know

```
$ docker --version
Docker version 20.10.12, build e91ed57
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

**Comment by joanhey** [comment]
Tested with 21.10, as 20.04 is EOL, and still fail.

I will add Amp to 21.10 to check if it's the free disk space.

**Comment by joanhey** [comment]
After check the results.
Nginx is working without problems with 21.10.
But not Workerman.

So perhaps will be necessary to change the dockerfiles affected.
Adding update and upgrade in the same RUN line.

First we will wait for the Amp test.

**Comment by joanhey** [comment]
Amp with 21.10 worked without problems.
So the problem is related to the free disk space issue #6582

**Comment by joanhey** [comment]
The docker files:
AMP
```
FROM ubuntu:21.10

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -yqq && apt-get install -yqq software-properties-common > /dev/null
RUN LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php
RUN apt-get update -yqq > /dev/null && \
    apt-get install -yqq git unzip wget curl build-essential \
    php8.1-cli php8.1-mbstring php8.1-dev php8.1-xml php8.1-curl > /dev/null

# An extension is required!
# We deal with concurrencies over 1k, which stream_select doesn't support.
RUN wget http://pear.php.net/go-pear.phar --quiet && php go-pear.phar
#RUN apt-get install -y libuv1-dev > /dev/null
RUN apt-get install -y libevent-dev > /dev/null
#RUN pecl install uv-0.2.4 > /dev/null && echo "extension=uv.so" > /etc/php/8.1/cli/conf.d/uv.ini
RUN pecl install event-3.0.6 > /dev/null && echo "extension=event.so" > /etc/php/8.1/cli/conf.d/event.ini

ADD ./ /amp
WORKDIR /amp

COPY deploy/conf/* /etc/php/8.1/cli/conf.d/

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

RUN composer install --prefer-dist --optimize-autoloader --no-dev --quiet

EXPOSE 8080

CMD php /amp/vendor/bin/cluster /amp/server.php
```

Workerman
```
FROM ubuntu:21.10

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -yqq && apt-get install -yqq software-properties-common > /dev/null
RUN LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php
RUN apt-get update -yqq > /dev/null && \
    apt-get install -yqq php8.1-cli php8.1-mysql php8.1-xml > /dev/null

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

RUN apt-get install -y php-pear php8.1-dev libevent-dev git > /dev/null
RUN pecl install event-3.0.6 > /dev/null && echo "extension=event.so" > /etc/php/8.1/cli/conf.d/event.ini
 
COPY php-jit.ini /etc/php/8.1/cli/php.ini

ADD ./ /workerman
WORKDIR /workerman

RUN composer install --optimize-autoloader --classmap-authoritative --no-dev --quiet

EXPOSE 8080

CMD php /workerman/server.php start
```

Error with workerman:
```
workerman: Step 1/14 : FROM ubuntu:21.10
workerman:  ---> 42b6dc79eba8
workerman: Step 2/14 : ARG DEBIAN_FRONTEND=noninteractive
workerman:  ---> Using cache
workerman:  ---> 362cd738baf8
workerman: Step 3/14 : RUN apt-get update -yqq && apt-get install -yqq software-properties-common > /dev/null
workerman:  ---> Running in 96ed4da95f4c
workerman: W: GPG error: http://security.ubuntu.com/ubuntu impish-security InRelease: At least one invalid signature was encountered.
workerman: E: The repository 'http://security.ubuntu.com/ubuntu impish-security InRelease' is not signed.
workerman: W: GPG error: http://archive.ubuntu.com/ubuntu impish InRelease: At least one invalid signature was encountered.
workerman: E: The repository 'http://archive.ubuntu.com/ubuntu impish InRelease' is not signed.
workerman: W: GPG error: http://archive.ubuntu.com/ubuntu impish-updates InRelease: At least one invalid signature was encountered.
workerman: E: The repository 'http://archive.ubuntu.com/ubuntu impish-updates InRelease' is not signed.
workerman: W: GPG error: http://archive.ubuntu.com/ubuntu impish-backports InRelease: At least one invalid signature was encountered.
workerman: E: The repository 'http://archive.ubuntu.com/ubuntu impish-backports InRelease' is not signed.
workerman: Removing intermediate container 96ed4da95f4c
workerman: Docker build failed; terminating
workerman: Traceback (most recent call last):
workerman:   File "/FrameworkBenchmarks/toolset/utils/docker_helper.py", line 55, in __build
workerman:     raise Exception(token['errorDetail']['message'])
workerman: Exception: The command '/bin/sh -c apt-get update -yqq && apt-get install -yqq software-properties-common > /dev/null' returned a non-zero code: 100
workerman: Build time: 3s
```
