### ISSUE TITLE
Having some problems trying to run tests locally.

### ISSUE THREAD

**Issue by timuckun** [TechEmpower/FrameworkBenchmarks#8077]
I noticed that a lot of the ruby code is very outdated so I wanted to pull run the tests on my machine as they are and with the newer versions. I am having two odd problems. 

Running tests on MacOS Monterey M1 

One is that it can't find the framework rack 

https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Ruby/rack

I run 
```bash
./tfb --mode verify --test rack 
```
I get 

```bash
....
Exception: Unable to locate tests ['rack']
```

The second problem I get is that if a test depends on MySQL it fails. For example. Obviously this is from the benchmarks framework and not the ruby framework.

```bash
./tfb --mode verify --test roda-sequel
```

The error I get is 
```bash
techempower/mysql:latest: Step 1/7 : FROM mysql:8.0-debian
techempower/mysql:latest: Docker build failed; terminating
techempower/mysql:latest: Traceback (most recent call last):
techempower/mysql:latest:   File "/FrameworkBenchmarks/toolset/utils/docker_helper.py", line 55, in __build
techempower/mysql:latest:     raise Exception(token['errorDetail']['message'])
techempower/mysql:latest: Exception: no matching manifest for linux/arm64/v8 in the manifest list entries
techempower/mysql:latest: Build time: 2s
A fatal error has occurred
Traceback (most recent call last):
  File "/FrameworkBenchmarks/toolset/run-tests.py", line 234, in main
    any_failed = benchmarker.run()
  File "/FrameworkBenchmarks/toolset/benchmark/benchmarker.py", line 58, in run
    self.docker_helper.build_databases()
  File "/FrameworkBenchmarks/toolset/utils/docker_helper.py", line 306, in build_databases
    tag="techempower/%s" % db)
  File "/FrameworkBenchmarks/toolset/utils/docker_helper.py", line 55, in __build
    raise Exception(token['errorDetail']['message'])
Exception: no matching manifest for linux/arm64/v8 in the manifest list entries
Shutting down (may take a moment)
```

**Comment by volyrique** [comment]
All the `rack` test permutations are marked as broken - see [here](https://github.com/TechEmpower/FrameworkBenchmarks/blob/ec8216a383161f4b0f294006a653dad147a49487/frameworks/Ruby/rack/benchmark_config.json#L23) for an example. This means that the toolset ignores them, as if they don't exist; removing the tags would make the implementations visible again, of course.

As for your other issue, try changing [the first line of the MySQL dockerfile](https://github.com/TechEmpower/FrameworkBenchmarks/blob/ec8216a383161f4b0f294006a653dad147a49487/toolset/databases/mysql/mysql.dockerfile#L1) to `FROM mysql:8.0-oracle`.
